// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2vh17Tm7Eh5jTpaeK7OEXeidXIeJl1hU',
    appId: '1:324297539404:web:dc14d8d8ed6d63eb8319e9',
    messagingSenderId: '324297539404',
    projectId: 'chat-app-f6682',
    authDomain: 'chat-app-f6682.firebaseapp.com',
    storageBucket: 'chat-app-f6682.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu7oYk6ehvTnEu6Ezv903FlWwo8LxGoUI',
    appId: '1:324297539404:android:ca96d2ef91807cd58319e9',
    messagingSenderId: '324297539404',
    projectId: 'chat-app-f6682',
    storageBucket: 'chat-app-f6682.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNfMzVQ_dgQPhoKoqXftzmtIRHsLFsiPc',
    appId: '1:324297539404:ios:8d98fc29722ca3c68319e9',
    messagingSenderId: '324297539404',
    projectId: 'chat-app-f6682',
    storageBucket: 'chat-app-f6682.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNfMzVQ_dgQPhoKoqXftzmtIRHsLFsiPc',
    appId: '1:324297539404:ios:8d98fc29722ca3c68319e9',
    messagingSenderId: '324297539404',
    projectId: 'chat-app-f6682',
    storageBucket: 'chat-app-f6682.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2vh17Tm7Eh5jTpaeK7OEXeidXIeJl1hU',
    appId: '1:324297539404:web:d9d8c1084cb3354d8319e9',
    messagingSenderId: '324297539404',
    projectId: 'chat-app-f6682',
    authDomain: 'chat-app-f6682.firebaseapp.com',
    storageBucket: 'chat-app-f6682.appspot.com',
  );
}
